// Descriptor precompilation, via attributes, is delegated to this file in the Framework mod in order to keep the Shared
// Project clean and usable without any other assemblies; since the precompilation attributes (e.g. GenerateDescriptor)
// are themselves generated by the source generator, these should be kept out of the Core.

namespace StardewUI.Widgets
{
    // csharpier-ignore-start
    [GenerateDescriptor] partial class Banner { }
    [GenerateDescriptor] partial class Button { }
    [GenerateDescriptor] partial class CheckBox { }
    [GenerateDescriptor] partial class ColorPicker { }
    // TODO: Drop-down lists aren't supported because they are generic.
    //
    // This can still probably be optimized somewhat by just storing a map of the type definition to descriptor
    // definition and using MakeGenericType, although it will be slower and needs to be cached.
    //
    // Can also try to generate some commonly-used variants like int and string; no mechanism for that right now.
    [GenerateDescriptor] partial class Expander { }
    [GenerateDescriptor] partial class Frame { }
    [GenerateDescriptor] partial class GhostView { }
    [GenerateDescriptor] partial class Grid { }
    [GenerateDescriptor] partial class Image { }
    [GenerateDescriptor] partial class Label { }
    [GenerateDescriptor] partial class Lane { }
    [GenerateDescriptor] partial class Marquee { }
    [GenerateDescriptor] partial class NineGridPlacementEditor { }
    [GenerateDescriptor] partial class Panel { }
    [GenerateDescriptor] partial class ScrollableFrameView { }
    [GenerateDescriptor] partial class ScrollableView { }
    [GenerateDescriptor] partial class Scrollbar { }
    [GenerateDescriptor] partial class ScrollContainer { }
    [GenerateDescriptor] partial class SegmentedControl { }
    [GenerateDescriptor] partial class Slider { }
    [GenerateDescriptor] partial class Spacer { }
    [GenerateDescriptor] partial class Tab { }
    [GenerateDescriptor] partial class TextInput { }
    [GenerateDescriptor] partial class TinyNumberLabel { }
    // csharpier-ignore-end
}

namespace StardewUI.Widgets.Keybinding
{
    // csharpier-ignore-start
    [GenerateDescriptor] partial class KeybindListEditor { }
    [GenerateDescriptor] partial class KeybindView { }
    // csharpier-ignore-end
}
